name: 🚀 Deploy to InfinityFree

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload to InfinityFree
    runs-on: ubuntu-latest
    steps:
      - name: 📥 Checkout code
        uses: actions/checkout@v3

      - name: 📤 FTP Deploy
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:
          server: ${{ secrets.ftpupload.net }}
          username: ${{ secrets.if0_39516049 }}
          password: ${{ secrets.Ibyp5o53nhBwUW }}
          server-dir: /htdocs/
